### ISSUE TITLE
BERT embeddings

### ISSUE THREAD

**Issue by OfirArviv** [SUDA-LA/ucca-parser#2]
Hi,

Reading your paper I noticed you used BERT embedding in it and (I suppose) because of that, got better results, especially on the ,multilingual settings. Do you have any plan to incorporate the usage of BERT embeddings to the code in this repository?

Thanks

**Comment by HMJW** [comment]
The old version of the code uses tensorflow bert (https://github.com/google-research/bert) to extract fixed bert embeddings and save them to the disk, which makes running inconvenient. So I am not planning to release the code. But I will release a version of incorporating the usage of pytorch bert (https://github.com/huggingface/pytorch-pretrained-BERT)  in the near future.
