### ISSUE TITLE
using your model to parse passages in Russian

### ISSUE THREAD

**Issue by lovodkin93** [SUDA-LA/ucca-parser#5]
Hello,
I would like to use your model to parse UCCA trees of passages in Russian.
Do you happen to know if your model supports other languages?
Thank you!

**Comment by HMJW** [comment]
I'm sorry that the model doesn't support Russian because of the lack of training corpus. As far as I know, there are only English, German and French training corpus.

**Comment by lovodkin93** [comment]
Oh, that's no problem.
We have just annotated a little corpus in Russian.
What I meant to ask is, given we have annotated passages in Russian, will it be possible to train the model for Russian?

**Comment by HMJW** [comment]
Yes. I think there should be no problem if annotated passages are provided.

**Comment by lovodkin93** [comment]
great, thanks!
